-- MySQL Script generated by MySQL Workbench
-- 05/05/20 10:38:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBTienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBTienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBTienda` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DBTienda` ;

-- -----------------------------------------------------
-- Table `DBTienda`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Tienda` (
  `IdTienda` INT NOT NULL AUTO_INCREMENT,
  `RazonSocial` VARCHAR(45) NULL,
  `Ruc` BIGINT NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdTienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Sucursal` (
  `IdSucursal` INT NOT NULL,
  `IdTienda` INT NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdSucursal`),
  INDEX `fk_Sucursal_Tienda_idx` (`IdTienda` ASC),
  CONSTRAINT `fk_Sucursal_Tienda`
    FOREIGN KEY (`IdTienda`)
    REFERENCES `DBTienda`.`Tienda` (`IdTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Cliente` (
  `IdCliente` INT NOT NULL,
  PRIMARY KEY (`IdCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Personal` (
  `IdPesona` INT NOT NULL,
  `Nombre` VARCHAR(60) NULL,
  `Apellido` VARCHAR(60) NULL,
  `FecNac` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  `TipoDocumento` VARCHAR(45) NULL,
  `NumDocumento` INT NULL,
  `Area` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`IdPesona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Usuario` (
  `IdUsuario` INT NOT NULL,
  `IdPesonal` INT NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `TipoUsuario` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `fk_Usuario_Personal1_idx` (`IdPesonal` ASC),
  CONSTRAINT `fk_Usuario_Personal1`
    FOREIGN KEY (`IdPesonal`)
    REFERENCES `DBTienda`.`Personal` (`IdPesona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`TipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`TipoProducto` (
  `IdTipoProducto` INT NOT NULL AUTO_INCREMENT,
  `TipoProducto` VARCHAR(60) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdTipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Categoria` (
  `IdCategoria` INT NOT NULL AUTO_INCREMENT,
  `IdTipoProducto` INT NOT NULL,
  `Categoria` VARCHAR(65) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdCategoria`),
  INDEX `fk_Categoria_TipoProducto1_idx` (`IdTipoProducto` ASC),
  CONSTRAINT `fk_Categoria_TipoProducto1`
    FOREIGN KEY (`IdTipoProducto`)
    REFERENCES `DBTienda`.`TipoProducto` (`IdTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Producto` (
  `IdProducto` INT NOT NULL AUTO_INCREMENT,
  `IdCategoria` INT NOT NULL,
  `Codigo` BIGINT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `StockMinTienda` DECIMAL(7,2) NULL,
  `StockMinGeneral` DECIMAL(7,2) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Imagen` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`IdCategoria` ASC),
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`IdCategoria`)
    REFERENCES `DBTienda`.`Categoria` (`IdCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Proveedor` (
  `IdProveedor` INT NOT NULL AUTO_INCREMENT,
  `RazonSocial` VARCHAR(45) NULL,
  `TipoDocumento` VARCHAR(45) NULL,
  `NumDocumento` BIGINT NULL,
  `Rublo` VARCHAR(45) NULL,
  `NumCelular` VARCHAR(12) NULL,
  `Telf` VARCHAR(12) NULL,
  `Correo` VARCHAR(65) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Compra` (
  `IdCompra` INT NOT NULL,
  `IdUsuario` INT NOT NULL,
  `IdProveedor` INT NOT NULL,
  `TipoComprobante` VARCHAR(45) NULL,
  `SerieCompro` VARCHAR(45) NULL,
  `NumCompro` VARCHAR(45) NULL,
  `Fecha` DATETIME NULL,
  `Asunto` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `EstadoCom` TINYINT NULL,
  `Impuesto` VARCHAR(45) NULL,
  `TotalCompra` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdCompra`),
  INDEX `fk_Compra_Usuario1_idx` (`IdUsuario` ASC),
  INDEX `fk_Compra_Proveedor1_idx` (`IdProveedor` ASC),
  CONSTRAINT `fk_Compra_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBTienda`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Proveedor1`
    FOREIGN KEY (`IdProveedor`)
    REFERENCES `DBTienda`.`Proveedor` (`IdProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`DetalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`DetalleCompra` (
  `IdDetalleCompra` INT NOT NULL,
  `IdCompra` INT NOT NULL,
  `IdProducto` INT NOT NULL,
  `Cantidad` DECIMAL(7,2) NULL,
  `PrecioCompra` DECIMAL(7,2) NULL,
  `CodigoBarra` BIGINT NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdDetalleCompra`),
  INDEX `fk_DetalleCompra_Compra1_idx` (`IdCompra` ASC),
  INDEX `fk_DetalleCompra_Producto1_idx` (`IdProducto` ASC),
  CONSTRAINT `fk_DetalleCompra_Compra1`
    FOREIGN KEY (`IdCompra`)
    REFERENCES `DBTienda`.`Compra` (`IdCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleCompra_Producto1`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `DBTienda`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Venta` (
  `IdVenta` INT NOT NULL,
  `IdSucursal` INT NOT NULL,
  `IdCliente` INT NOT NULL,
  PRIMARY KEY (`IdVenta`),
  INDEX `fk_Venta_Sucursal1_idx` (`IdSucursal` ASC),
  INDEX `fk_Venta_Cliente1_idx` (`IdCliente` ASC),
  CONSTRAINT `fk_Venta_Sucursal1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `DBTienda`.`Sucursal` (`IdSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Cliente1`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `DBTienda`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`DetalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`DetalleVenta` (
  `IdDetalleVenta` INT NOT NULL,
  `IdVenta` INT NOT NULL,
  `Producto_IdProducto` INT NOT NULL,
  PRIMARY KEY (`IdDetalleVenta`),
  INDEX `fk_DetalleVenta_Venta1_idx` (`IdVenta` ASC),
  INDEX `fk_DetalleVenta_Producto1_idx` (`Producto_IdProducto` ASC),
  CONSTRAINT `fk_DetalleVenta_Venta1`
    FOREIGN KEY (`IdVenta`)
    REFERENCES `DBTienda`.`Venta` (`IdVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleVenta_Producto1`
    FOREIGN KEY (`Producto_IdProducto`)
    REFERENCES `DBTienda`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`Permiso` (
  `IdPermiso` INT NOT NULL,
  `Permiso` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdPermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`DetallePermiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`DetallePermiso` (
  `IdDetallePermiso` INT NOT NULL,
  `IdPermiso` INT NOT NULL,
  `IdUsuario` INT NOT NULL,
  PRIMARY KEY (`IdDetallePermiso`),
  INDEX `fk_DetallePermiso_Permiso1_idx` (`IdPermiso` ASC),
  INDEX `fk_DetallePermiso_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_DetallePermiso_Permiso1`
    FOREIGN KEY (`IdPermiso`)
    REFERENCES `DBTienda`.`Permiso` (`IdPermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePermiso_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBTienda`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTienda`.`IngresoTienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTienda`.`IngresoTienda` (
  `IdIngresoTienda` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` DECIMAL(7,2) NULL,
  `IdSucursal` INT NOT NULL,
  `IdUsuario` INT NOT NULL,
  `PrecioVentaXMenor` DECIMAL(7,2) NULL,
  `PrecioVentaXMayor` DECIMAL(7,2) NULL,
  `Estado` TINYINT NULL,
  `IdDetalleCompra` INT NOT NULL,
  PRIMARY KEY (`IdIngresoTienda`),
  INDEX `fk_IngresoTienda_Sucursal1_idx` (`IdSucursal` ASC),
  INDEX `fk_IngresoTienda_Usuario1_idx` (`IdUsuario` ASC),
  INDEX `fk_IngresoTienda_DetalleCompra1_idx` (`IdDetalleCompra` ASC),
  CONSTRAINT `fk_IngresoTienda_Sucursal1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `DBTienda`.`Sucursal` (`IdSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IngresoTienda_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `DBTienda`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IngresoTienda_DetalleCompra1`
    FOREIGN KEY (`IdDetalleCompra`)
    REFERENCES `DBTienda`.`DetalleCompra` (`IdDetalleCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
